theme: jekyll-theme-cayman
title: Getting Started with ArcGIS Online
description: A short tutorial demostrating some of the functionality of ArcGIS Online. We will explore how to then turn this map into a ArcGIS Story Map. Note: This lesson was developed for Religion in Modern Europe in Spring 2018. 
level: Beginner
